FROM golang:1.23-alpine3.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

WORKDIR /app

RUN CGO_ENABLED=0 GOOS=linux go build -o messenger main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/messenger .

# Создаём директории для хранения файлов
RUN mkdir -p /app/storage/files
RUN mkdir -p /app/storage/temp

# Устанавливаем правильные права доступа
RUN chmod -R 755 /app/storage

EXPOSE 8080

CMD ["./messenger"]

