FROM golang:1.23-alpine3.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

WORKDIR /app

RUN CGO_ENABLED=0 GOOS=linux go build -o messenger main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/messenger .

EXPOSE 8080

CMD ["./messenger"]

