/**
 * @fileoverview gRPC-Web generated client stub for messenger
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.3
// source: key_exchange_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.messenger = require('./key_exchange_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.messenger.KeyExchangeServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.messenger.KeyExchangeServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.messenger.InitKeyExchangeRequest,
 *   !proto.messenger.InitKeyExchangeResponse>}
 */
const methodDescriptor_KeyExchangeService_InitKeyExchange = new grpc.web.MethodDescriptor(
  '/messenger.KeyExchangeService/InitKeyExchange',
  grpc.web.MethodType.UNARY,
  proto.messenger.InitKeyExchangeRequest,
  proto.messenger.InitKeyExchangeResponse,
  /**
   * @param {!proto.messenger.InitKeyExchangeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.messenger.InitKeyExchangeResponse.deserializeBinary
);


/**
 * @param {!proto.messenger.InitKeyExchangeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.messenger.InitKeyExchangeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.messenger.InitKeyExchangeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.messenger.KeyExchangeServiceClient.prototype.initKeyExchange =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/messenger.KeyExchangeService/InitKeyExchange',
      request,
      metadata || {},
      methodDescriptor_KeyExchangeService_InitKeyExchange,
      callback);
};


/**
 * @param {!proto.messenger.InitKeyExchangeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.messenger.InitKeyExchangeResponse>}
 *     Promise that resolves to the response
 */
proto.messenger.KeyExchangeServicePromiseClient.prototype.initKeyExchange =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/messenger.KeyExchangeService/InitKeyExchange',
      request,
      metadata || {},
      methodDescriptor_KeyExchangeService_InitKeyExchange);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.messenger.CompleteKeyExchangeRequest,
 *   !proto.messenger.CompleteKeyExchangeResponse>}
 */
const methodDescriptor_KeyExchangeService_CompleteKeyExchange = new grpc.web.MethodDescriptor(
  '/messenger.KeyExchangeService/CompleteKeyExchange',
  grpc.web.MethodType.UNARY,
  proto.messenger.CompleteKeyExchangeRequest,
  proto.messenger.CompleteKeyExchangeResponse,
  /**
   * @param {!proto.messenger.CompleteKeyExchangeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.messenger.CompleteKeyExchangeResponse.deserializeBinary
);


/**
 * @param {!proto.messenger.CompleteKeyExchangeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.messenger.CompleteKeyExchangeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.messenger.CompleteKeyExchangeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.messenger.KeyExchangeServiceClient.prototype.completeKeyExchange =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/messenger.KeyExchangeService/CompleteKeyExchange',
      request,
      metadata || {},
      methodDescriptor_KeyExchangeService_CompleteKeyExchange,
      callback);
};


/**
 * @param {!proto.messenger.CompleteKeyExchangeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.messenger.CompleteKeyExchangeResponse>}
 *     Promise that resolves to the response
 */
proto.messenger.KeyExchangeServicePromiseClient.prototype.completeKeyExchange =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/messenger.KeyExchangeService/CompleteKeyExchange',
      request,
      metadata || {},
      methodDescriptor_KeyExchangeService_CompleteKeyExchange);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.messenger.GetKeyExchangeParamsRequest,
 *   !proto.messenger.GetKeyExchangeParamsResponse>}
 */
const methodDescriptor_KeyExchangeService_GetKeyExchangeParams = new grpc.web.MethodDescriptor(
  '/messenger.KeyExchangeService/GetKeyExchangeParams',
  grpc.web.MethodType.UNARY,
  proto.messenger.GetKeyExchangeParamsRequest,
  proto.messenger.GetKeyExchangeParamsResponse,
  /**
   * @param {!proto.messenger.GetKeyExchangeParamsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.messenger.GetKeyExchangeParamsResponse.deserializeBinary
);


/**
 * @param {!proto.messenger.GetKeyExchangeParamsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.messenger.GetKeyExchangeParamsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.messenger.GetKeyExchangeParamsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.messenger.KeyExchangeServiceClient.prototype.getKeyExchangeParams =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/messenger.KeyExchangeService/GetKeyExchangeParams',
      request,
      metadata || {},
      methodDescriptor_KeyExchangeService_GetKeyExchangeParams,
      callback);
};


/**
 * @param {!proto.messenger.GetKeyExchangeParamsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.messenger.GetKeyExchangeParamsResponse>}
 *     Promise that resolves to the response
 */
proto.messenger.KeyExchangeServicePromiseClient.prototype.getKeyExchangeParams =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/messenger.KeyExchangeService/GetKeyExchangeParams',
      request,
      metadata || {},
      methodDescriptor_KeyExchangeService_GetKeyExchangeParams);
};


module.exports = proto.messenger;

